version: "3.8"
services:
    service-socks:
        image: docker-htsp:latest
        container_name: docker-htsp
        restart: always   
        networks: 
            - service-net
        ports: 
            - "3128:3128"
        volumes:
            - source: ./tsocks.conf
              target: /etc/tsocks.conf
              type: bind 
        command: "/run.sh"

networks:
     service-net:
         driver: bridge

